### ISSUE TITLE
前端优化雪碧图使用说明

### ISSUE THREAD

**Issue by kvkens** [iuap-design/blog#194]
# 前端优化雪碧图使用说明

> 基于gulp-css-spriter修改来达到简便按需使用

## 1. 安装

- 安装本地gulp`npm install gulp --save-dev`
- 安装雪碧图优化过的插件`npm install gulp-css-spriter-param`

## 2. 配置

- 配置`gulpfile.js`修改如下：

```js

    var gulp = require('gulp'),
        spriter = require('gulp-css-spriter-param');


    //处理雪碧图任务
    gulp.task('sprite', function() {
        return gulp.src(['./css/style.css'])
            .pipe(spriter({
                'spriteSheet': './images/spritesheet.png', //这是雪碧图自动合成的图。 很重要
                'pathToSpriteSheetFromCSS': '../images/spritesheet.png' //这是在css引用的图片路径，很重要
            }))
            .pipe(gulp.dest('./css/')); //最后生成出来
    });

```

- 修改`package.json`来配置插件启动

```js
"scripts": {
  "css" : "gulp sprite"
},
```

## 3. 使用

- 新建页面`index.html`内容如下：

```html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="./css/style.css">
  <title>css-spiter</title>
</head>
<body>
<div class="wrap">
  <i class="icon icon-01"></i>
  <i class="icon icon-02"></i>
  <i class="icon icon-03"></i>
  <i class="icon icon-04"></i>
  <i class="icon icon-05"></i>
  <i class="icon icon-06"></i>
</div>
</body>
</html>

```

> 里面的<i>就是我们要显示的背景小图标的容器

- 新增样式文件`style.css`

```css
* {
	margin: 0;
	padding: 0;
	font-size: 12px;
	font-family: 'microsoft yahei';
}

.wrap {
	width: 1200px;
	height: 700px;
	margin: 0 auto;
	background: #ececec;
}

.icon {
	width: 200px;
	height: 200px;
	display: inline-block;
	margin: 60px 90px;
}

.icon-01 {
	background: url('../images/icon01.png?__sprite') no-repeat;
}

.icon-02 {
	background: url('../images/icon02.png?__sprite') no-repeat;
}

.icon-03 {
	background: url('../images/icon03.png?__sprite') no-repeat;
}

.icon-04 {
	background: url('../images/icon04.png?__sprite') no-repeat;
}

.icon-05 {
	background: url('../images/icon05.png?__sprite') no-repeat;
}

.icon-06 {
	background: url('../images/icon06.png?__sprite') no-repeat;
}

```

> 主要观察`.icon`相关要作为雪碧图合并内容，对应的小图片png存放好

这样打开的时候是会显示一堆可爱的小图标的，但是这样明显请求过多需要使用修改过的插件进行优化

**插件会自动寻找`?__sprite`后缀的图片进行雪碧图制作，这也是核心所在，不写的话会自动忽略**

这个时候需要我们来运行`npm run css`来自动制作雪碧图

便已完毕之后css发生了变化，并且会多出一个图片

```css
* {
	margin: 0;
	padding: 0;
	font-size: 12px;
	font-family: 'microsoft yahei';
}

.wrap {
	width: 1200px;
	height: 700px;
	margin: 0 auto;
	background: #ececec;
}

.icon {
	width: 200px;
	height: 200px;
	display: inline-block;
	margin: 60px 90px;
}

.icon-01 {
	background: url('../images/spritesheet.png') no-repeat;
	background-position: -0px -0px;
}

.icon-02 {
	background: url('../images/spritesheet.png') no-repeat;
	background-position: -200px -0px;
}

.icon-03 {
	background: url('../images/spritesheet.png') no-repeat;
	background-position: -0px -200px;
}

.icon-04 {
	background: url('../images/spritesheet.png') no-repeat;
	background-position: -200px -200px;
}

.icon-05 {
	background: url('../images/spritesheet.png') no-repeat;
	background-position: -400px -0px;
}

.icon-06 {
	background: url('../images/spritesheet.png') no-repeat;
	background-position: -400px -200px;
}
```

## 4. API

请参考原版API本功能只添加后缀名去处理雪碧图.
想执行雪碧图任务在图片后面加载此标记即可`?__sprite`

`xxx.png?__sprite`

[API](https://github.com/MadLittleMods/gulp-css-spriter)

[css-spriter.zip](https://github.com/iuap-design/blog/files/982202/css-spriter.zip)
