### ISSUE TITLE
轻松处理环绕文字

### ISSUE THREAD

**Issue by ahua52** [iuap-design/blog#210]
先配上项目上的效果图

#第一种方案
如果你急需要解决问题，请直接跳到下面第二种方案
工作中遇到一个需要前端实现自定印章的场景，初始处理借助了Airen的博客的方法，参考地址：http://www.w3cplus.com/css3/css-secrets/circular-text.html。核心技术技术点是运用svg画圆.
```js
          let el = document.getElementsByClassName("demo");
          var NS = "http://www.w3.org/2000/svg";
          
          var svg = document.createElementNS(NS, "svg");

          svg.setAttribute("viewBox", "-5 -30 150 150");
          //定义处理印章最外面的circle
          var wrapcircle = document.createElementNS(NS, "path");
          wrapcircle.setAttribute("d", "M0,45 a66,66 0 1,1 0,1z");
          wrapcircle.setAttribute("id", "maxcircle");

         //定义处理circle 即文字环绕曲线
          var circle = document.createElementNS(NS, "path");
          circle.setAttribute("d", "M15,50 a50,50 0 1,1 0,1z");
          circle.setAttribute("id", "circle");
          var text = document.createElementNS(NS, "text");
          var textPath = document.createElementNS(NS, "textPath");
          textPath.setAttributeNS("http://www.w3.org/1999/xlink", 'xlink:href', '#circle');
          textPath.textContent = el.textContent;
          text.appendChild(textPath);
          
          svg.appendChild(circle);
          svg.appendChild(text);
          svg.appendChild(wrapcircle);
          
          el.textContent = '';
          el.appendChild(svg);
```
```html
       <div className="demo">
             有文化专用章
        </div>
```

```css
.circular {
    width: 1.2rem;
    height: 1.2rem;
}

.circular svg {
	display: block;
	overflow: visible;
	transition: 10s linear transform;
}
#maxcircle {
	stroke: #f39576;
	stroke-width: .1rem;
}
.circular text { fill: currentColor }
.circular path { fill: none; }
```

在js代码中，我们又看到`M15,50 a50,50 0 1,1 0,1z`这样的代码，svg手写的最大痛苦就在于此，调路径参数。印章大小稍微调节一下，就要花费一些时间调路径参数。想shi有木有。
放弃这种方法的最根本的原因还是，我的印章文字来自后台返回数据，返回数据有一定的延时，当数据还没有返回，提前执行了渲染svg，印章变渲染不出来，延时处理也不是很理想，
当然不可否认，这是一种挺好的方法，在熟悉svg的情况下，可以任意的处理图形。

#第二种方案
第二种方案在使用上要轻松愉快的多，代码量也不多，源码请参照
https://github.com/ahua52/react-circleText/blob/master/circleText.js
重点介绍下用法

```js
import circleText from circleText
let option = {
    tagName:"demo",
    radius:60
}
circleType(option);

/**
  options = {
    tagName:"demo", // 目标元素的类名
    radius:60       // 圆半径
    dir: 1,         // 文字环绕方向[1，-1]
    position: 'relative',
    fitText: false,   //自适应屏幕
    fontSizeUnit:'px',  //自适应屏幕字体单位
    kompressor:1, //自适应缩放比
    fontSize: 20  //默认文字大小
  }
*/

```

```html
    <div className="demo-wrap">
       <div className="demo">
             有文化专用章
        </div>
     </div>
```

```css
.demo-wrap {
    height: .95rem;
    width: .95rem;
    border: .06rem solid #f39576;
    border-radius: 50%;
}
```

在运用上更加的简洁,本篇博客重在介绍circleText的用法，具体代码详情日后详谈。
参考文章
https://1stwebdesigner.com/set-text-on-a-circle-with-css/
http://circletype.labwire.ca/
